name: nasa_picture_of_the_day
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  injectable: ^2.4.2
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true


